Delete [tblProduct]
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51433A','01  Pallet  Plastic Can','AB MCC 44 X 56 PLASTIC, CAN','BALL') 

INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51433','01  Pallet  Plastic Can','BALL 44 X 56 PLASTIC, CAN','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51434A','04  Top Frame  Plastic','AB 44 X 56 X 1 PLASTIC','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51433B','01  Pallet  Plastic Can','BALL 44 X 56 PLASTIC, CAN - REPAIR BASE','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51434','04  Top Frame  Plastic','BALL 44 X 56 X 1 PLASTIC','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51398A','09  Sheet  Light Plastic','AB MCC 44 X 56 TYPAR','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51436','14  Pallet  Plastic End','BALL 44 X 56 PLASTIC, END','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51436A','14  Pallet  Plastic End','AB MCC 42 X 38 PLASTIC, END','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51439','04  Top Frame  Plastic','COMPETITOR TOP FRAME','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51441','04  Top Frame  Plastic','BALL 44 X 56 X 1 PLASTIC 2 X  BAR','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51442','04  Top Frame  Plastic','BALL 44 X 56 X 1 PLASTIC 1 X  BAR','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51444','01  Pallet  Plastic Can','BALL 44 X 56 PLASTIC, CAN','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51445','01  Pallet  Plastic Can','BPS 44 X 56 TALL BLOCK, CAN E X ','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51449','01  Pallet  Plastic Can','UNKNOWN','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51450','09  Sheet  Light Plastic','BALL 44 X 56 X 0.25 PLASTIC CC E X ','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51451','09  Sheet  Light Plastic','BALL 44 X 56 X 0.50 PLASTIC','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51452','09  Sheet  Light Plastic','BALL 44 X 56 TYPAR','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51453','09  Sheet  Light Plastic','COMPETITOR SHEET','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51455','04  Top Frame  Plastic','BALL 44 X 56 X 1 PLASTIC','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51459','01  Pallet  Plastic Can','COMPETITOR PALLET','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51461','09  Sheet  Light Plastic','MCC 44 X 56 TYPAR','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51462','04  Top Frame  Plastic','MCC 44 X 56 X 1 PLASTIC','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51462A','04  Top Frame  Plastic','MCC 44 X 56 X 1 PLASTIC','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51467','14  Pallet  Plastic End','BALL 124 X 110 PLASTIC, END M X ','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51468','09  Sheet  Light Plastic','BALL 44 X 56 X 0.25 4\ RADIUS M X ','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('515100','01  Pallet  Plastic Can','R X M ORBIS 44 X 56 PLASTIC CAN PL','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('515150','01  Pallet  Plastic Can','R X M ORBIS M X  HN 44 X 56 PLAS CAN','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('515200','04  Top Frame  Plastic','R X M ORBIS 44 X 56 PLASTIC TOP FR','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('515250','04  Top Frame  Plastic','UNKNOWN','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('515300','09  Sheet  Light Plastic','R X M ORBIS \ RADIUS STD TIER','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('515350','09  Sheet  Light Plastic','R X M ORBIS 4\ RADIUS E X P TIER S','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('515400','09  Sheet  Light Plastic','R X M ORBIS 4\ RADIUS CAP TIER S','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('515450','09  Sheet  Light Plastic','R X M ORBIS 4\ RADIUS M X  TIER SH','BALL') 
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('515500','14  Pallet  Plastic End','R X M ORBIS 40 X 48 PLASTIC, END','BALL')

INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514010','01  Pallet  Plastic Can','PALLET, CAN 44 X 56 - PLASTIC','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51419','02  Pallet  Wood Can','SP 44  X  56 WOOD CAN','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514006','02  Pallet  Wood Can','PALLET, CAN 44 X 56 - 9 BLOCK WOOD','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514002','04  Top Frame  Plastic','TOP FRAME, 44 X 56 - PLASTIC','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514002TB','04  Top Frame  Plastic','TOP FRAME, 44 X 56 - PLASTIC THICK BLACK','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514020','05  Top Frame  Wood','TOP FRAME, 44 X 56 - WOOD','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514005','06  Sheet  Heavy Paper','DUPLICATE OF 80005','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514005BD','06  Sheet  Heavy Paper','SHEET, .060- HEAVY GAUGE PAPER BLUE DIAMOND CA ONLY','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51405','06  Sheet  Heavy Paper','SHEET, .050 -.080 - HEAVY GAUGE PAPER','BMP')
--INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51417','07  Sheet  Light Paper','DUPLICATE OF 80017','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51417MK','07  Sheet  Light Paper','SHEET, .025 -.045 - LIGHT GAUGE PAPER MILWAUKEE ONLY','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51417','07  Sheet  Light Paper','SHEET, .025 -.045 - LIGHT GAUGE PAPER','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51404','08  Sheet  Heavy Plastic','DUPLICATE OF 80004','BMP')
--04','08  Sheet  Heavy Plastic','SHEET, .050 -.065 - HEAVY GAUGE PLASTIC','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51403','09  Sheet  Light Plastic','DUPLICATE OF 80003','BMP')
--INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51457','09  Sheet  Light Plastic','DUPLICATE OF 80057','BMP')
--INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51403','09  Sheet  Light Plastic','SHEET, .025 -.030 - LIGHT GAUGE PLASTIC','BMP')
--INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51457','09  Sheet  Light Plastic','SHEET, .030 - LIGHT GAUGE PLASTIC','BMP')
--INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51442','10  Waffleboard','DUPLICATE OF 80042','BMP')
--INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51442','10  Waffleboard','WAFFLE BOARD','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51443','11  Foam','DUPLICATE OF 80043','BMP')
--INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51443','11  Foam','SHEET, FOAM','BMP')
--INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51441','12  Layerboard','DUPLICATE OF 80041','BMP')
--INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51441','12  Layerboard','LAYER BOARD, CORRUGATE','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514002C','13  Competitor Material','TOP FRAME ,44 X 56 - PLASTIC COMPETITOR','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514006C','13  Competitor Material','PALLET CAN, 44  X  56 9 BLOCK WOOD COMPETITOR','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514010C','13  Competitor Material','PALLET CAN, 44  X  56 PLASTIC COMPETITOR','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('514020C','13  Competitor Material','TOP FRAME, 44  X  56 WOOD - COMPETITOR','BMP')
INSERT [dbo].[tblProduct]([Item_Number],[Item_Group],[Description],[Customer_Group]) VALUES('51420','16  Used Top','SP 44  X  56 USED TOP','BMP')

