//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoreDBEntities : DbContext
    {
        public CoreDBEntities()
            : base("name=CoreDBEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomerReference> tblCustomerReferences { get; set; }
        public virtual DbSet<tblFoodSale> tblFoodSales { get; set; }
        public virtual DbSet<tblMaterial_Handling> tblMaterial_Handling { get; set; }
        public virtual DbSet<tblPlant> tblPlants { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProduct_Reference> tblProduct_Reference { get; set; }
        public virtual DbSet<tblReturn> tblReturns { get; set; }
        public virtual DbSet<tblWarehouse> tblWarehouses { get; set; }
        public virtual DbSet<tblBeverageSale> tblBeverageSales { get; set; }
    }
}
