//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerInfo
    {
        public long CustomerInfoId { get; set; }
        public string CustomerCode { get; set; }
        public string STATUS { get; set; }
        public string TERMS { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<bool> IS_CREDIT_HOLD { get; set; }
        public Nullable<bool> IS_CREDI_TWATCH { get; set; }
        public string PRICELIST { get; set; }
        public string CLASS_PLANNER { get; set; }
        public string PLANNER_BUYER_NAME { get; set; }
        public string REGION { get; set; }
        public Nullable<bool> IS_PO_REQUIRED { get; set; }
        public Nullable<bool> IS_TAXABLE { get; set; }
        public string TAXZONE { get; set; }
        public string FED_TAX_ID { get; set; }
        public string ST_TAX_ID { get; set; }
        public string JDE_CODE_25 { get; set; }
        public string JDE_CODE_25_DESC { get; set; }
        public string INV_CONSOLIDATION { get; set; }
        public string EDI_EMAIL { get; set; }
        public string INV_PRINT_OPT { get; set; }
        public string IS_CURENT_CUST { get; set; }
        public string ARR_ACCOUNT { get; set; }
        public string REMIT_TO { get; set; }
        public string INVOICE_EMAIL { get; set; }
        public string SITE { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual tblCustomerReference tblCustomerReference { get; set; }
    }
}
