//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReturn
    {
        public long ReturnId { get; set; }
        public string Transfer { get; set; }
        public string Shipper_PO { get; set; }
        public string Pro_Num { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public string To_NT_Code { get; set; }
        public string To_Name { get; set; }
        public string From_NT_Code { get; set; }
        public string From_Ball_ID { get; set; }
        public string From_Name { get; set; }
        public string Item_NT { get; set; }
        public string Item_Ball { get; set; }
        public long Quantity { get; set; }
        public long Scrap { get; set; }
        public long Special_Cleaning { get; set; }
        public long Repair { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual tblCustomerReference tblCustomerReference { get; set; }
        public virtual tblProduct_Reference tblProduct_Reference { get; set; }
    }
}
